<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    style="
      margin: auto;
      background: none;
      display: block;
      shape-rendering: auto;
      animation-play-state: running;
      animation-delay: 0s;
    "
    width="200px"
    height="200px"
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
  >
    <path
      d="M14 50A36 36 0 0 0 86 50A36 38 0 0 1 14 50"
      :fill="gitLoadingIconColor"
      stroke="none"
      style="animation-play-state: running; animation-delay: 0s"
    >
      <animateTransform
        attributeName="transform"
        type="rotate"
        dur="1.2048192771084336s"
        repeatCount="indefinite"
        keyTimes="0;1"
        values="0 50 51;360 50 51"
        style="animation-play-state: running; animation-delay: 0s"
      ></animateTransform>
    </path>
    <!-- [ldio] generated by https://loading.io/ -->
  </svg>
</template>

<script>
export default {
  data() {
    return {
      gitLoadingIconColor: window.vueData.git_loading_icon_color,
    };
  },
};
</script>

<style></style>
